
# i3 doesn't have "normalizations" feature that why we disable them here.
# But the feature is very helpful.
# Normalizations eliminate all sorts of weird tree configurations that don't make sense.
# Give normalizations a chance and enable them back.
enable-normalization-flatten-containers = false
enable-normalization-opposite-orientation-for-nested-containers = false

# Mouse follows focus when focused monitor changes
on-focused-monitor-changed = ['move-mouse monitor-lazy-center']
on-focus-changed = ['move-mouse window-lazy-center']

start-at-login = true

[mode.main.binding]
# See: https://nikitabobko.github.io/AeroSpace/goodness#open-a-new-window-with-applescript
#cmd-enter = '''exec-and-forget osascript -e '
#tell application "WezTerm"
#    activate
#end tell'
#'''

alt-h = 'focus left'
alt-j = 'focus down'
alt-k = 'focus up'
alt-l = 'focus right'

alt-shift-h = 'move left'
alt-shift-j = 'move down'
alt-shift-k = 'move up'
alt-shift-l = 'move right'

# Consider using 'join-with' command as a 'split' replacement if you want to enable normalizations
ctrl-cmd-n = 'split horizontal'
ctrl-cmd-m = 'split vertical'

alt-shift-f = 'fullscreen'

alt-y = 'layout v_accordion'               # 'layout stacking' in i3
alt-u = 'layout h_accordion'               # 'layout tabbed' in i3
alt-i = 'layout tiles horizontal vertical' # 'layout toggle split' in i3

cmd-alt-f = 'layout floating tiling' # 'floating toggle' in i3

# Not supported, because this command is redundant in AeroSpace mental model.
# See: https://nikitabobko.github.io/AeroSpace/guide#floating-windows
#alt-space = 'focus toggle_tiling_floating'

# `focus parent`/`focus child` are not yet supported, and it's not clear whether they
# should be supported at all https://github.com/nikitabobko/AeroSpace/issues/5
# alt-a = 'focus parent'

f1 = 'workspace 1'
f2 = 'workspace 2'
f3 = 'workspace 3'
f4 = 'workspace 4'
f5 = 'workspace 5'
f6 = 'workspace 6'
f7 = 'workspace 7'
f8 = 'workspace 8'
f9 = 'workspace 9'
f10 = 'workspace 10'

shift-f1 = 'move-node-to-workspace 1'
shift-f2 = 'move-node-to-workspace 2'
shift-f3 = 'move-node-to-workspace 3'
shift-f4 = 'move-node-to-workspace 4'
shift-f5 = 'move-node-to-workspace 5'
shift-f6 = 'move-node-to-workspace 6'
shift-f7 = 'move-node-to-workspace 7'
shift-f8 = 'move-node-to-workspace 8'
shift-f9 = 'move-node-to-workspace 9'
shift-f10 = 'move-node-to-workspace 10'

ctrl-cmd-6 = 'move-workspace-to-monitor prev'
ctrl-cmd-9 = 'move-workspace-to-monitor next'

ctrl-cmd-c = 'reload-config'

cmd-shift-semicolon = 'mode service'

alt-r = 'mode resize'

[mode.service.binding]
esc = ['reload-config', 'mode main']
r = ['flatten-workspace-tree', 'mode main']
f = ['layout floating tiling', 'mode main']
backspace = ['close-all-windows-but-current', 'mode main']

ctrl-alt-h = ['join-with left', 'mode main']
ctrl-alt-j = ['join-with down', 'mode main']
ctrl-alt-k = ['join-with up', 'mode main']
ctrl-alt-l = ['join-with right', 'mode main']


[mode.resize.binding]
h = 'resize width -50'
j = 'resize height +50'
k = 'resize height -50'
l = 'resize width +50'
enter = 'mode main'
esc = 'mode main'

[[on-window-detected]]
if.app-id = 'com.github.wez.wezterm'
run = ['move-node-to-workspace 2']

[[on-window-detected]]
if.app-id = 'com.vivaldi.Vivaldi'
run = ['move-node-to-workspace 1']

[[on-window-detected]]
if.app-id = 'company.thebrowser.Browser'
run = ['move-node-to-workspace 5']

[[on-window-detected]]
if.app-id = 'com.microsoft.teams2'
run = ['move-node-to-workspace 7']


[[on-window-detected]]
if.app-id = 'com.microsoft.StorageExplorer'
run = ['move-node-to-workspace 7']


[[on-window-detected]]
if.app-id = 'com.todesktop.230313mzl4w4u92'
run = ['move-node-to-workspace 3']


[[on-window-detected]]
if.app-id = 'com.firstversionist.polypane'
run = ['move-node-to-workspace 4']

[[on-window-detected]]
if.app-id = 'com.usebruno.app'
run = ['move-node-to-workspace 6']

[[on-window-detected]]
if.app-id = 'org.SuperSlicer/'
run = ['move-node-to-workspace 7']

[[on-window-detected]]
if.app-id = 'com.citrix.receiver.icaviewer.mac'
run = ['move-node-to-workspace 7']

# [gaps]
# inner.horizontal = 10
# inner.vertical = 10
# outer.left = 10
# outer.bottom = 10
# outer.top = 10
# outer.right = 10
